### ISSUE TITLE
Added a custom configuration for the glow of other mod ores

### ISSUE THREAD

**Issue by Hanwei233** [Apothicon02/Glowing-Ores#3]
Can you add a config for adding the glow effect of the ores of other mods?

**Comment by Apothicon02** [comment]
You can already add any block you want.

**Comment by PinkJojoKun** [comment]
Hey, might be a dumb question, but how can I do that? If I start entering other ores in the same format, e.g., `"create:zinc_ore":10,` (from the Create Mod, which is also installed), it crashes, saying it couldn't start properly.

**Comment by gvancamp** [comment]
I have just attempted this myself and also am getting this error.

Glore (glore) has failed to load correctly
java.lang.RuntimeException: Could not locate create:zinc_ore, this could be due to a typo in the block name or the mod the block is added by being incompatible with Glore's method of making blocks emit light.
